### ISSUE TITLE
Not there yet

### ISSUE THREAD

**Issue by VRKommando** [cbuchner1/driver_leap#3]
I still have the problem with the last 2 releases where the driver isn't installed properly
Since update 3 I have been using the edited method where you put in the actual directory of the steam folder

Release #6 still doesn't fully cover everyone
Edit & #7

**Comment by cbuchner1** [comment]
Care to elaborate on any specifics about who is not yet covered by Alpha #6?

Von meinem iPhone gesendet

**Comment by vaibhavaggarwal007** [comment]
Hi,

I would just like to add that the driver is also not working properly on my PC since the update #3.

**Comment by VRKommando** [comment]
Yes, well you see my SteamDir is located at E:\Steam, and I have tried every release, with no luck, so I decided to run each after uninstalling and installing the next release, I ran the register_driver.cmd manually with command prompt, to read what its telling me without it flashing for a split second.

So after doing so, I get to read the following message:

`The system cannot find the path specified.
The system cannot find the path specified.
The system cannot find the path specified.
        0 file(s) copied.

C:\Program Files (x86)\SteamVR Leap Motion driver>`

So I decided to try editing the register_driver.cmd file and adding my steam directory manually
It worked perfectly and I was able to get it working on release #3

Everything was great after doing so, and all other releases 1-2 & 4-6 did not work for me
So there is still a detection problem, maybe make release #7 have you manually input the steam directory? to fix that?

**Comment by amym** [comment]
Hi. I Couldn't get the latest release to work. Installed it via exe and also tried putting it in the steam dir. Let me know if you have any suggestions. Thanks.

**Comment by jimmyleet** [comment]
Amazing work thanks for letting me enjoy some vive games :) I still haven't had any luck since release #3 tho installation wise working.
Tried the latest one #6 and installed no issues just not detected on steam VR anymore :)
Keep up the amazing work tho

**Comment by cbuchner1** [comment]
I will try some installations on virgin PCs that just received Steam and SteamVR installed on various locations...

Von meinem iPhone gesendet

**Comment by jimmyleet** [comment]
I got no errors apart from having to manually remove older version, it installed with no issues just steamVR isn't detecting controllers.

**Comment by cbuchner1** [comment]
I get it, the "leap" subdirectory has to exist because it provides the base name for the driver. With the current setup, Steam will be looking for a file called driver_SteamVR Leap Motion driver.dll   which of course is not found (error 103).

Alpha #7 should be the one to finally fix this mess.

**Comment by thomasvt1** [comment]
I got it working, its actually very simple.

1. Go to your "vrpathreg" for me its located at;
`C:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\win32`

2.  Shift-rightlick and click "open command window here"

3. Execute "vrpathreg" by dragging the file into the cmd. or just retype the name in cmd

4. Then you'll see all external drivers listed;
![image](https://cloud.githubusercontent.com/assets/2271011/15820494/0ada040a-2bea-11e6-9972-cb830b18d216.png)

5. If you dont see `C:\Program Files\SteamVR Leap Motion driver`
listed you can add it with the following command:
`vrpathreg adddriver "C:\Program Files\SteamVR Leap Motion driver\bin\Win64"`

6. Repeat the vrpathreg command to see if it's listed now.

**Comment by cbuchner1** [comment]
When I follow your suggestion I get this error in the steamvr logs

Mon Jun 06 2016 13:47:17.739 - Unable to load driver Win32 from C:\Program
Files\SteamVR Leap Motion driver\bin\Win32\bin\win32\driver_Win32.dll.

Mon Jun 06 2016 13:47:17.739 - Unable to load driver Win32 because of error
103. Skipping.

Mon Jun 06 2016 13:47:17.739 - Unable to load driver Win64 from C:\Program
Files\SteamVR Leap Motion driver\bin\Win64\bin\win32\driver_Win64.dll.

Mon Jun 06 2016 13:47:17.739 - Unable to load driver Win64 because of error
103. Skipping.


I will have to reinstate the "leap" subdirectory and append it to the path
given to adddriver. Then things should be working.


Christian




2016-06-06 13:27 GMT+02:00 Thomas <notifications@github.com>:

**Comment by RonSijm** [comment]
I installed Alpha Release #6 on a "virgin pc", no previous versions, and it did not work.

I then followed the instructions of  thomasvt1, and the driver was indeed not listed.
I then manually installed the driver like thomasvt1, but that did not help.

I'm not exactly sure if I'm supposed to see anything anywhere, like extra vr controllers listed in my SteamVR, but I don't. I've tested it by opening 'fantastic contraption' and trying it out, but that did not work.

Note: I did not have any external drivers, and I see on thomasvt1 his screenshot that he has 4. Do I need more?

I can provide log files if you need to know anything... but I'm not sure where / which... I'm using windows 10 x64.

**Comment by thomasvt1** [comment]
I updated to Alpha #6 and it doesn't work anymore - reinstalled Alpha #5 and it works again.

**Comment by Tyrminaotr** [comment]
don't work for me either.  win 10 x64 with riftcat

i still have to use realise 3
06.06.2016 20:40 "RonSijm" <notifications@github.com> napisał(a):

**Comment by VRKommando** [comment]
#7 still does not work

The only way I can get it to work is by using #3
and editing the CFG file and adding my steam directory manually

like so:
`@echo off
cls
SET mypath=%~dp0

REM detect Steam install directory
for /f "tokens=2*" %%A in ('reg query hku /e /c /v /f SteamPath /t REG_SZ /s 2^>^NUL') DO (
	set SteamPath=%%B
	goto :start
)
:start

REM register driver
"E:\Steam\steamapps\common\SteamVR\bin\win32\vrpathreg.exe" adddriver "%mypath:~0,-1%\leap"

REM backup steamvr.vrsettings in steam config dir
copy "E:\Steam\config\steamvr.vrsettings" "%SteamPath%\config\steamvr.vrsettings.leap_backup"

REM copy steamvr.vrsettings to steam config dir
copy "%mypath:~0,-1%\steamvr.vrsettings" "E:\Steam\config\"
`

**Comment by amym** [comment]
Hi. I got v7 working by following these instructions https://www.reddit.com/r/oculus/comments/4l7dc4/how_to_use_open_vr_with_leap_motion/d3yj93a

> V 7. Run the setup.exe and it will install normaly on "C:\Program Files\SteamVR Leap Motion driver\". Now go to this location and copy all Files "config_tool.exe","leap.vrsettings", and the Folder/Dir "leap". After that move to your Steam Installations Folder, SteamApps->common->OpenVR or SteamVR depens on the Date and Time when it got installed. Now open the Folder "drivers", and paste the copyd Files. Then open the "leap.vrsettings" and copy all text and paste it into the File "steam.vrsettings", or rename the "leap.vrsettings" and replace the old "steam.vrsettings" File.You can find it inside the Folder "config" which should be in the Steam Installations Folder. After that start your Steam, open SteamVR and you should have 2 Green Controllers, when not try to hold your both hands right infront of the Leap Motion Sensor so it should detect them.

**Comment by VRKommando** [comment]
#8 does not work as well, I am still using the v3 edited txt method

**Comment by cbuchner1** [comment]
Works on 2 out of 3 PCs I've been testing on ;-)

A friend's PC is still giving me trouble. Nonstandard steam library location.

Von meinem iPhone gesendet

**Comment by VRKommando** [comment]
Cant you make it where you can choose to browse the location manually in the installation window, or having the steam leap driver installed directly in the steam folder

**Comment by ddutchie** [comment]
This is glorious!!. I managed to get a htc dk1 with no wireless dongles so controllers are currently a little usless. Thanks to this I was able to get room scale setup completed with nothing but my trusty leapmotion taped to the front of the vive. Epic. Thanks.

**Comment by Ibsn87** [comment]
wow, finally come back to this after being busy the past few days. @amym has nailed it! Followed that instruction and I now have 2 green controllers. Fantastic, cannot wait to try it out now! Thanks !!
